#!/bin/bash

#choose number of sticks

function getNumSticks {
      read -p "How many stick you want?" numSticks
      while [[ $numSticks -lt 10 ]]
      do
          echo "Sorry. You need 10 sticks or more"
          read -p "How many sticks you want man?" numSticks
      done
      echo $numSticks "is the number of sticks"
}
#decides who goes first

function whoGoesFirst {
   #read -p turnFirst

   
   while [[ 1 == 1  ]] #forever loop
  read -p "Type in u for user if you want to go first, or c for computer if you want to go second after me"  turnFirst

      do
	#computer
        if [[ "$turnFirst"  == "c" ]]
           then
             break
            fi
        #user   
        if [[ "$turnfirst" == "u" ]]
	  then 
		break
      
         fi
         done 
         echo $turnFirst "goes first"  
 }
funtion computerTurn(){
        
        if [[  "$n%5" -eq 0 ]]
        then
             n=$( (n-1) )
        else
             f="$n%5"
             n=$( (n-f) )
        fi
        i=1
        while [[ $i -le $n ]]
        do
        	echo -n "|"
        	i=$((i+1))

	done
	echo -e -n "($n)\n"

}
#main
#welcome
echo Welcome to the great game of sticks
#do intro
#choose number of sticks
n=`getNumSticks`
#choose who goes first
t=`whoGoesFirst`
#game loops util gameover is 0. gameover is 0 when someone wins
while [[ gameover -eq 0 ]]
do
echo "n = $n"
i=1
while [[ $i -le $n ]]
do
   echo -n "|"
   i=$((i+1))

done
echo -e -n "($n)\n"

done

