#!/bin/bash

#choose number of sticks

function getNumSticks {
      read -p "How many stick you want?" numSticks
      while [[ $numSticks -lt 10 ]]
      do
          echo "Sorry. You need 10 sticks or more"
          read -p "How many sticks you want man?" numSticks
      done
      echo $numSticks "is the number of sticks"
}
#decides who goes first

function whoGoesFirst {
   #read -p turnFirst

   
   while [[ 1 == 1  ]] #forever loop
  do 
  read -p "Type in u for user if you want to go first, or c for computer if you want to go second after me"  turnFirst

      
	
	#computer
        if [[ "$turnFirst"  == "c" ]]
           then
             break
       fi     
        #user   
       if [[ "$turnfirst" == "u" ]]
	  then 
		break
      
         fi
         done 
         echo $turnFirst 
 }
#This isthe computer Turn function. If the number of sticks is divisble by 5 it takes 1 stick
#Else it takes modulo 5 amount of sticks
function computerTurn(){
        
        if [[ ( ($1%5) ) -eq 0 ]]
        then
             $1=$( ($1-1) )
        else
             f=$( ($1%5) )
             $1=$( ($1-f) )
        fi
        i=1
        while [[ $i -le $1 ]]
        do
        	echo -n "|"
        	i=$((i+1))

	done
	echo -e -n "($1)\n"

}
#user turn 
function userTurn {
read -p "Please type in the number of sticks you need. Do not take more than 4 sticks" userSticks
if [[ $userSticks -ge 1 ]] && [[ $userSticks -le 4 ]]
then
    $1=$( ($1-userSticks) )
else
  echo  "You should type an amount between 1 and 4."
  if [[ $userSticks -ge 1 ]] && [[ $userSticks -le 4 ]]
  then 
    $1=$( ($1-userSticks) )
  else
   echo "You have forfeited the game"
   $1=0
   fi
fi
 i=1
        while [[ $i -le $1 ]]
        do
                echo -n "|"
                i=$((i+1))

        done
        echo -e -n "($1)\n"

}

function didComputerWin {
if [[ $1 -eq 0 ]]
then
  echo I won
  $1=-1
fi
}
function didUserWin {
if [[ $1 -eq 0 ]]
then
  echo you won
  $1=-1
fi
}





#main
#welcome
echo Welcome to the great game of sticks
#do intro
#choose number of sticks
n=`getNumSticks`
#choose who goes first
t=`whoGoesFirst`
#game loops util gameover is 0. gameover is 0 when someone wins
while [[ gameover -eq 0 ]]
	do
	echo "n = $n"

	if [[ "$t" == "c" ]]
		then 
       		ct=`computerTurn $n`
       		cw=`didComputerWin $ct`
       
	#checks to see if computer won
       if [[ $cw -eq -1 ]]
       then 
 	  $gameover=1
          break
       fi

       #user Turn
      ut=`userTurn $ct`
       if [[ $ut -eq -1 ]]
       then
	  $gameover=1
          break
       fi

       #checks to see if the user won
       uw=`didUserWin $ut`
	if [[ $uw -eq -1 ]]
       then
	$gameover=1
          break
       fi 
       $n=$ut
  fi
       if [[ "$t" == "u" ]]
    	 uta=`userTurn $n`
     		 if [[ $uta -eq -1 ]]
       then

	$gameover=1
          break
       		fi


     $uwa=`didUserWin $uta`
	if [[ $uwa -eq -1 ]]
       then
	  $gameover=1
          break
       fi

      cta=`computerTurn $uta` 
      cwa=`didComputerWin $cta`
	if [[ $cwa -eq 1 ]]
       then
	$gameover=1
          break
       fi
      $n=$cta
fi
done

